### ISSUE TITLE
Maintaining and the future of stylelint-a11y

### ISSUE THREAD

**Issue by carlosjeurissen** [ronilaukkarinen/stylelint-a11y#2]
Seems there is both https://github.com/YozhikM/stylelint-a11y/ and https://github.com/ronilaukkarinen/stylelint-a11y/ published on NPM.

As proposed here, lets attempt to move to a single listing being maintained.
https://github.com/YozhikM/stylelint-a11y/issues/69

**Comment by ronilaukkarinen** [comment]
Interesting. This repo is used in dozens of projects of ours here at [dude](https://github.com/digitoimistodude), actually [this comment](https://github.com/stylelint/stylelint/issues/6212#issuecomment-1705744761) is exactly our perspective.

**Comment by rollecode** [comment]
As a reference, here's my take:

> Maintainer of [@ronilaukkarinen/stylelint-a11y](https://github.com/ronilaukkarinen/stylelint-a11y) fork speaking 👋 As stated https://github.com/ronilaukkarinen/stylelint-a11y/issues/2#issuecomment-1866348056 this could have been my comment from word to word. We've gone through your path as well here at [Dude](https://github.com/digitoimistodude) and I decided to fork the repo couple of years ago because of this very reason. I wanted it so that the repo would not be owned by my company but myself, to underline the fact it was started by a person.
> 
> Our approach is to just maintain [the fork](https://github.com/ronilaukkarinen/stylelint-a11y) it as-is, because we used it in [dozens of projects](https://github.com/digitoimistodude/devpackages/blob/700f926e30cee894d41f465274c5108c7a5b74ca/package.json#L13) in our company. Maybe we can co-exist somehow.
